version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: goCrudPostgres
    environment:
      POSTGRES_USER: goCrud
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: goCrud-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:


# docker compose up -d db
# docker ls
# docker volume rm <your_project_name>_postgres_data
